---
apiVersion: v1
kind: ConfigMap
metadata:
  name: adsb-sync-cfg
  namespace: planespotter
data:
  config.ini: |
    [main]
    redis_server = redis-server
    adsb_server_poll_url = https://public-api.adsbexchange.com/VirtualRadar/AircraftList.json
    adsb_poll_filter = ?fRegS=N
    adsb_type = poll