---
apiVersion: v1
kind: ConfigMap
metadata:
  name: planespotter-app-cfg
  namespace: planespotter
data:
  config.cfg: |
    LISTEN_PORT = '80'
    DATABASE_URL = 'mysql'
    DATABASE_USER = 'planespotter'
    DATABASE_PWD = 'VMware1!'
    DATABASE = 'planespotter'
    REDIS_HOST = 'redis-server'
    REDIS_PORT = '6379'